### ISSUE TITLE
Footer: Code for Romania logo not loading

### ISSUE THREAD

**Issue by czmole** [code4romania/civichq-client#102]
The img src points to https://code4.ro/images/logo-full-gray.png which does not exist anymore

**Comment by lrdTnc** [comment]
that link is working. (and also currently in app)

![image](https://user-images.githubusercontent.com/6780432/55531307-721a3b80-56b2-11e9-83cf-d5588571c91f.png)

**Comment by czmole** [comment]
not really, one is .png the other .svg , centrucivic.ro links to png which is not their anymore
I will change my PR anyway to that version of svg

**Comment by czmole** [comment]
**there

**Comment by czmole** [comment]
I have removed my PR, the problem is not in the github codebase but on the server where it links to png not to svg as it should

**Comment by aniri** [comment]
this issue seems to be fixed. closing :)
