### ISSUE TITLE
URL proiect

### ISSUE THREAD

**Issue by razvanpavel** [code4romania/civichq-client#13]

**Comment by razvanpavel** [comment]
`/#/profile/65` -> `/#/65/nume-aplicatie`

Zi-mi daca e bataie de cap, nu arde, but it's a good practice

**Comment by andrap11** [comment]
Din cate citesc nu e inca supported de angular 2 router, i'll investigate some more.

**Comment by andrap11** [comment]
Ok, avem acum pe un app  -> /#/apps/65/nume-aplicatie, iar pe Despre centru - > /#/about.
 Let me know if it's ok.
