### ISSUE TITLE
Add a Technologies section on the app page

### ISSUE THREAD

**Issue by aniri** [code4romania/civichq-client#62]
Add a new content section for technologies in the [app details page](http://www.centrucivic.ro/#/apps/58/CentruCivic) 

The info about the technologies field should be returned by the API https://github.com/code4romania/civichq-api/issues/81

Best practices

- codebase language should be English
- we :two_hearts: unit tests

**Comment by paul-ghiran** [comment]
![image](https://user-images.githubusercontent.com/38477423/53285881-049ff480-376f-11e9-8f48-3fcfbbe4232e.png)

Implementation idea

**Comment by AndreiGr** [comment]
Will be pairing up with @paul-ghiran on this ticket

**Comment by aniri** [comment]
> ![image](https://user-images.githubusercontent.com/38477423/53285881-049ff480-376f-11e9-8f48-3fcfbbe4232e.png)
> 
> Implementation idea

looks great!
