### ISSUE TITLE
[bug] icons not centered in carousel control buttons 

### ISSUE THREAD

**Issue by raduflp** [code4romania/civichq-client#77]
Glyphicons are not centered in the carousel left/right control buttons 
![image](https://user-images.githubusercontent.com/7570412/51788415-7db72680-2186-11e9-831a-ce31681f5e7b.png)

**Comment by lrdTnc** [comment]
oops, just noticed this. After I upgraded to angular 7 the carousel control buttons look different now:

![image](https://user-images.githubusercontent.com/6780432/54481546-a1215800-483e-11e9-9c2e-ba589322de4b.png)
