### ISSUE TITLE
[bug] when the search option from the top menu is expanded, the menu alignment is wrong

### ISSUE THREAD

**Issue by aniri** [code4romania/civichq-client#92]
Fix top menu navbar - after the new items where added, fixes should be done to the width of the menu.

![capture](https://user-images.githubusercontent.com/1358055/53987111-b7d1fb80-4128-11e9-8c1c-4994094a6b70.JPG)

Best practices

- codebase language should be English

**Comment by lrdTnc** [comment]
I think just editing the width of the menu won't fix the problem... (actually padding)
The padding right and left matches the padding of the page content. 

Also since we have the new buttons, the alignment is bad even without search menu expanded. 
See here: 
![header](https://user-images.githubusercontent.com/6780432/54069519-86108000-4261-11e9-8a97-d748b10ee5f4.gif)

**Comment by aniri** [comment]
The behaviour of the menu resizing should be adjusted to handle the new items. Currently it has three phazes:

- centru civic complete logo + complete menu items
![cc1](https://user-images.githubusercontent.com/1358055/54496524-046fc080-48f9-11e9-89f3-8322b815fdf6.jpg)
- just icon for logo + complete menu items
![cc2](https://user-images.githubusercontent.com/1358055/54496531-0f2a5580-48f9-11e9-8e10-8f54ef5d98bf.jpg)
- complete logo + hamburger button for menu
![cc3](https://user-images.githubusercontent.com/1358055/54496540-2701d980-48f9-11e9-860f-319f1c3ff557.jpg)

The resizing rules should be changed so as the menu will always display on a single row. Please change the moment for switching to icon logo and then to complete logo & hamburger menu.

**Comment by paul-ghiran** [comment]
This site uses a different kind of search box, which might fix the issue. How do we feel about something like this being implemented?

**Comment by paul-ghiran** [comment]
http://osteopathicheritage.org/# missed the link, sorry 
 :man_facepalming:
